Changed where drush.yml is written to, so it can be used to set the site's uri.
codeenigma/ce-deploy pull request #451
Opened 2024-03-27 14:10 UTC by rupertj

I've been trying to use drush.yml to set the site's URL in drush. Without this, URLs in the search index, and sitemap.xml end up with a domain of 'default' when generated in code called by drush.

Currently, the task that generates drush.yml writes a file to set the uri option to sites/default/drush.yml, but this makes no difference to the site's URI.

As per [this comment from Moshe](https://github.com/drush-ops/drush/issues/3121#issuecomment-364802730), drush.yml in a site directory is valid, but too late to set the uri. Setting it in drush/drush.yml does work. I've tried this on stage by moving the generated file to that path, and it works as expected.

As URI is the only option that ce-deploy currently supports in drush.yml, here's a PR to move the file so that option works.

2024-03-27 15:13 UTC, rupertj commented
Hi @gregharvey - any chance of a review? Ta :)

2024-04-03 17:58 UTC, gregharvey requested changes
Hmm, we'll need both behaviours I think. This is invoked in a loop you see:
* https://github.com/codeenigma/ce-deploy/blob/1.x/roles/config_generate/config_generate-drupal8/tasks/main.yml#L12

So we'll need to respect the fact not everyone will want to do this. Indeed, we may have other users relying on the current behaviour. I think we're going to need a separate task in `main.yml` of this role, called something like `Generate global drush.yml file.`

That task would be able to just place this file without bothering with a loop, maybe the `with_first_found` would look more like this?

```yaml
  with_first_found:
    - "{{ playbook_dir }}/drush/{{ build_type }}.{{ config_generate_drupal.drush_settings_file_name }}.j2"
    - "{{ _ce_deploy_build_dir }}/drush/{{ build_type }}.{{ config_generate_drupal.drush_settings_file_name }}"
    - "{{ _ce_deploy_build_dir }}/drush/{{ config_generate_drupal.drush_settings_file_name }}"
    - "drush.yml.j2"
```

That way if you provide a `drush/prod.drush.yml.j2` file, for example, it will be placed in the correct location as `drush.yml`. We probably need some kind of flag to enable it via a `when` clause too, maybe `global_drush: false` as the default, but if you set it to `true` this task will run?

Also, are these mutually exclusive options, or can you have `drush/drush.yml` *and* `web/sites/default/drush.yml`?

Thanks!

2024-04-04 14:33 UTC, gregharvey commented
PS - can you also please make a PR into `devel` as well? That way we can test it before putting it live. :slightly_smiling_face:

2024-06-04 16:23 UTC, rupertj commented
Closing this, as I found a simpler solution for it in the end: I committed a symlink to H&F's codebase from drush/drush.yml to web/sites/default/drush.yml.

2024-06-04 16:23 UTC, closed without merging